[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y nginx php-fpm"
]

[phases.install]
cmds = ["cp nginx.conf /etc/nginx/nginx.conf"]

[start]
cmd = "service php8.1-fpm start && nginx -g 'daemon off;'"