[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y nginx php-fpm",
    "php -v"
]

[phases.install]
cmds = ["cp nginx.conf /etc/nginx/nginx.conf"]

[start]
cmd = "php-fpm -D && nginx -g 'daemon off;'"