[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y nginx php-fpm php"
]

[phases.install]
cmds = ["cp nginx.conf /etc/nginx/nginx.conf"]

[start]
cmd = "/usr/sbin/php-fpm -D && nginx -g 'daemon off;'"